### ISSUE TITLE
Solution: Python could not be found. Run without arguments to proceed!

### ISSUE THREAD

**Issue by MDProz** [mbcrump/PPPwn-Windows-Instructions#1]
Hello

I don't know if this is a solution in itself but for the order: 
=> `python3 pppwn.py --interface=Ethernet --fw=900`
The command states: 
=> _Python is nowhere to be found. Execute without arguments to proceed!_

I just replaced `Python3` with `py` or `py -3` and it worked. 
I don't know why the command with `Python3` doesn't work. 

With command:
=> `py -3 pppwn.py --interface=Ethernet --fw=900`
or
=> `py pppwn.py --interface=Ethernet --fw=900`

No problem, everything works. 
Thank you.

**Comment by B-Dem** [comment]
python3 is only for linux, he should change the command from `python3 pppwn.py` to `python pppwn.py`

**Comment by MDProz** [comment]
Right, thank you for the clarification.
